sp16-hw2/config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  put 'age', to: 'pages#person'
  post 'stringify', to: 'pages#stringify'
  get 'me', to: 'me#me'

end

sp16-hw2/app/controllers/concerns/foobar.rb
class Foobar
  # ENTER CODE FOR Q2 HERE
  def initialize(baz)
  	@baz = baz
  end

  def bar(cat, bar)
  	return cat.to_s + @baz + bar[:sat].to_s
  end

end

sp16-hw2/app/controllers/concerns/person.rb
class Person
	def initialize(name, age)
		@name = name
		@age = age
		@nickname = name[0..3]
	end

	def introduce
		"#{@name} is #{@age} years old."
	end

	def birth_year
		2016 - @age.to_i
	end

	def nickname
		@nickname
	end
end

sp16-hw2/app/controllers/me_controller.rb
class MeController < ApplicationController
	def me
	end
end

sp16-hw2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    foo = Foobar.new "baz"
    @baz = foo.bar :cat, sat: :dat, dat: :sat
  end

  def stringify
    if params[:name] == ""
      @text = "You are nothing!"
    else
      name = params[:name]
      adjective = params[:adjective]
      @text = "#{name} is so #{adjective}"
    end

  end

  def age
  end

  def person
    @name = params[:name]
    @age = params[:age]
    person = Person.new @name, @age
    @birthYear = person.birth_year
    @nickname = person.nickname
    @introduction = person.introduce
  end
end

sp16-hw2/app/helpers/me_helper.rb
module MeHelper
end

sp16-hw2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

sp16-hw2/app/views/me/me.html.erb
<h1>My name is Simon Cao and I was born in France.</h1>

sp16-hw2/app/views/pages/age.html.erb
<h1>REROUTE ME!</h1>

sp16-hw2/app/views/pages/home.html.erb
    <h1>Hello There! Welcome to homework 2!</h1>
<p>What a beautiful homepage!</p>
<p>Good thing this isn't the web design decal.</p>

<h1>Question 1</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag stringify_path do %>
  <%= label_tag :name, "Your Name here!" %>
  <%= text_area_tag :name %>
  <%= label_tag :adjective, "An adjective here!" %>
  <%= text_area_tag :adjective %>
  <%= submit_tag "Stringify!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

<h1>Question 2</h1>

<p>Your result</p>
<%= @baz %>

<h1>Question 3</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag age_path, method: :put do %>
  <%= label_tag :name, "Your name:" %>
  <%= text_area_tag :name %>
  <%= label_tag :age, "Your age:" %>
  <%= text_area_tag :age %>
  <%= submit_tag "Submit!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

sp16-hw2/app/views/pages/person.html.erb
<%= @introduction + " He was born in #{@birthYear} and his nickname is #{@nickname}." %>

sp16-hw2/app/views/pages/stringify.html.erb
<%= @text %>