sp16-hw4/config/routes.rb
Rails.application.routes.draw do
  get 'dogs/index'

  get "users", to: "users#index"
  get "users/new", to: "users#new"
  get "users/:id", to: "users#show", as: :user
  post "users", to: "users#create"

  get "dogs", to: "dogs#index"
  get "dogs/new", to: "dogs#new"
  get "dogs/:id", to: "dogs#show", as: :dog
  post "dogs", to: "dogs#create"
end

sp16-hw4/app/models/dog.rb
class Dog < ActiveRecord::Base
  # The User model.  Our abstraction to access the database.

  validates :name, presence: true # Validates that there is a name
  validates :age, presence: true
end

sp16-hw4/app/models/user.rb
class User < ActiveRecord::Base
  # The User model.  Our abstraction to access the database.

  validates :name, presence: true # Validates that there is a name
end

sp16-hw4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sp16-hw4/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
  	@dogs = Dog.all
  end

  def new
  	@dog = Dog.new
  end

  def create
    @dog = Dog.create(dog_params)
    if @dog.save
      redirect_to @dog
    else
      render "new"
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :age)
  end
end

sp16-hw4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # The controller for users.  Makes an implicit call to render "views/users/method_name.html.erb" at the end of every method.

  def index
    @users = User.all # Get's all the Users in our database and assigns it the the instance variable @user.
  end

  def new
    @user = User.new #Creates an empty user object.
  end

  def create
    @user = User.create(user_params)
    if @user.save #If saving the user was successful
      redirect_to @user #Go to the show view of the user
    else
      render "new" #Go to the new view for the user
    end
  end

  def show
    @user = User.find(params[:id]) # Query for the user with the id that is in params
  end

  private

  def user_params
    params.require(:user).permit(:name, :email) #Returns a hash that was the value of "name" and "email" from the value of "user" in params.
  end
end

sp16-hw4/app/helpers/application_helper.rb
module ApplicationHelper
end

sp16-hw4/app/helpers/dogs_helper.rb
module DogsHelper
end

sp16-hw4/app/helpers/index_helper.rb
module IndexHelper
end

sp16-hw4/app/helpers/users_helper.rb
module UsersHelper
end

sp16-hw4/app/views/dogs/index.html.erb
<h1>Dogs in the Database</h1>
<% @dogs.each do |u| %> 
  Name: <p> <%= link_to u.name, dog_path(u) %> </p> 
  Age : <p> <%= u.age %> </p> 
<% end %>

<%= link_to "new", dogs_new_path %>

sp16-hw4/app/views/dogs/new.html.erb
<h1>Create New</h1>
  <%= form_for @dog do |f| %>
    Name: <%= f.text_field :name %>
    Age: <%= f.text_field :age %>
    <%= f.submit %>
  <% end %>


<p>Find me in app/views/dogs/new.html.erb</p>

sp16-hw4/app/views/dogs/show.html.erb
Name: <%= @dog.name %>
Age: <%= @dog.age %>

sp16-hw4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sp15Hw4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

sp16-hw4/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

sp16-hw4/app/views/users/index.html.erb
<h1>Users in the Database</h1>
<% @users.each do |u| %> <!-- Iterates through each user under the variable u -->
  Name: <p> <%= link_to u.name, user_path(u) %> </p> <!-- Show the users name-->
  Email : <p> <%= u.email %> </p> <!-- Show the users email -->
<% end %>
<%= link_to "new", users_new_path %> <!-- Create a link that appears as "new" that leads to users_new_path -->

sp16-hw4/app/views/users/new.html.erb
<h1>Create New</h1>
  <%= form_for @user do |f| %> <!-- Create form for user object -->
    Name: <%= f.text_field :name %> <!-- Create a text field that sends its value under the key name-->
    Email: <%= f.text_field :email %><!-- Create a text field that sends its value under the key email -->
    <%= f.submit %> <!-- Create submit button-->
  <% end %>


<p>Find me in app/views/users/new.html.erb</p>

sp16-hw4/app/views/users/show.html.erb
Name: <%= @user.name %>
Email: <%= @user.email %>